from __future__ import annotations

import argparse
import csv
import json
from dataclasses import replace
from datetime import datetime
from pathlib import Path

import pandas as pd

from backtest_lab.config import load_config
from backtest_lab.data import download_yfinance_prices, load_price_csv, split_adjusted_dividends
from backtest_lab.radar_core_pool_v1 import (
    RadarCoreResult,
    RadarCoreVariant,
    load_radar_core_members,
    radar_core_mid_small_calibrated_v1_variant,
    simulate_radar_core_pool,
)
from backtest_lab.sector_dynamic_pool_backtest import ThemeMember
from backtest_lab.simulation import BacktestResult, simulate_buy_and_hold


DEFAULT_RADAR_ROOT = r"C:\Users\zergv\Documents\Codex\2026-05-23\ai-stock-rotation-radar-https-docs"
DEFAULT_OUTPUT_ROOT = "outputs/sector_dynamic_pool/radar_core_pool_v1"
DEFAULT_CACHE_DIR = "backtest_cache/radar_core_pool_v1"


def main() -> None:
    parser = argparse.ArgumentParser(description="Run radar core member pool v1 in resumable batches.")
    parser.add_argument("--config", default="configs/ep05_universe.json")
    parser.add_argument("--radar-root", default=DEFAULT_RADAR_ROOT)
    parser.add_argument("--start-date", default="2022-01-03")
    parser.add_argument("--end-date", default="2023-12-29")
    parser.add_argument("--warmup-start", default="2020-01-01")
    parser.add_argument("--cache-dir", default=DEFAULT_CACHE_DIR)
    parser.add_argument("--output-root", default=DEFAULT_OUTPUT_ROOT)
    parser.add_argument("--themes", default="", help="Comma-separated theme names for staged runs. Empty means all primary themes.")
    parser.add_argument("--variant-filter", default="", help="Comma-separated variant ids to run. Empty means all variants.")
    parser.add_argument("--cache-only", action="store_true", help="Use existing CSV cache only and skip missing tickers.")
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()

    output_dir = Path(args.output_root) / "latest"
    output_dir.mkdir(parents=True, exist_ok=True)
    run_started = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    _write_step(output_dir, "load_config")

    config = load_config(args.config)
    radar_root = Path(args.radar_root)
    members = load_radar_core_members(radar_root / "data" / "theme_map.csv")
    if args.themes.strip():
        requested_themes = {theme.strip() for theme in args.themes.split(",") if theme.strip()}
        members = [member for member in members if member.theme in requested_themes]
    if not members:
        raise ValueError("No radar core members found from theme_map.csv")

    _write_step(output_dir, "download_or_load_price_cache")
    benchmark_tickers = ["0050.TW", "00631L.TW"]
    members, member_prices, skipped = _download_member_prices(
        members,
        start_date=args.warmup_start,
        end_date=args.end_date,
        cache_dir=args.cache_dir,
        cache_only=args.cache_only,
    )
    if args.cache_only:
        benchmark_prices = _load_cached_prices(benchmark_tickers, args.warmup_start, args.end_date, args.cache_dir)
    else:
        benchmark_prices = download_yfinance_prices(
            benchmark_tickers,
            start_date=args.warmup_start,
            end_date=args.end_date,
            cache_dir=args.cache_dir,
        )
    prices = {**member_prices, **benchmark_prices}
    dividends = {
        ticker: split_adjusted_dividends(prices[ticker], tuple(config.manual_splits.get(ticker, ())))
        for ticker in prices
    }

    asset_types = {ticker: "stock" for ticker in member_prices}
    asset_types.update({"0050.TW": "etf", "00631L.TW": "etf"})
    members_by_ticker = {member.ticker: member for member in members}

    _write_step(output_dir, "run_variants")
    completed = _read_completed(output_dir / "completed_variants.csv")
    variant_results: list[tuple[RadarCoreVariant, RadarCoreResult]] = []
    variant_filter = {item.strip() for item in args.variant_filter.split(",") if item.strip()}
    for variant in _variants():
        if variant_filter and variant.name not in variant_filter:
            continue
        if variant.name in completed and not args.force:
            _append_log(output_dir, variant.name, "skipped", "already_completed")
            continue
        try:
            result = simulate_radar_core_pool(
                name=variant.label,
                prices_by_ticker=member_prices,
                members_by_ticker=members_by_ticker,
                asset_types=asset_types,
                market_prices=benchmark_prices["0050.TW"],
                start_date=args.start_date,
                end_date=args.end_date,
                initial_cash=config.initial_cash_twd,
                cost_model=config.cost_model,
                variant=variant,
                dividend_series_by_ticker={ticker: dividends[ticker] for ticker in member_prices},
            )
            variant_results.append((variant, result))
            _write_variant_outputs(output_dir, variant, result)
            _append_completed(output_dir, variant, result.result)
            _append_log(output_dir, variant.name, "completed", f"return={result.result.total_return:.4f}")
        except Exception as error:  # noqa: BLE001 - runner records failures and continues.
            _append_failed(output_dir, variant, error)
            _append_log(output_dir, variant.name, "failed", str(error))

    _write_step(output_dir, "build_benchmarks")
    benchmarks = [
        simulate_buy_and_hold(
            name="0050 買進持有",
            ticker="0050.TW",
            prices=benchmark_prices["0050.TW"],
            asset_type="etf",
            start_date=args.start_date,
            end_date=args.end_date,
            initial_cash=config.initial_cash_twd,
            cost_model=config.cost_model,
            dividend_series=dividends["0050.TW"],
        ),
        simulate_buy_and_hold(
            name="0050正二 買進持有",
            ticker="00631L.TW",
            prices=benchmark_prices["00631L.TW"],
            asset_type="etf",
            start_date=args.start_date,
            end_date=args.end_date,
            initial_cash=config.initial_cash_twd,
            cost_model=config.cost_model,
            dividend_series=dividends["00631L.TW"],
        ),
    ]
    _write_summary(output_dir, variant_results, benchmarks, skipped, args, run_started)
    _write_step(output_dir, "done")
    print(f"OUTPUT_DIR={output_dir.resolve()}")


def _variants() -> list[RadarCoreVariant]:
    return [
        RadarCoreVariant(
            name="radar_core_v1_universal_profile_defaults",
            label="雷達核心成員池 v1 通用股票池預設參數",
            use_pool_profile_defaults=True,
        ),
        RadarCoreVariant(
            name="radar_core_v1_balanced_weekly",
            label="雷達核心成員池 v1 平衡週頻",
        ),
        RadarCoreVariant(
            name="radar_core_v1_attack_weekly",
            label="雷達核心成員池 v1 進攻週頻",
            top_theme_count=3,
            max_stocks_per_theme=2,
            max_single_weight=0.20,
            min_theme_score=0.08,
            min_stock_score=0.03,
            strong_bull_exposure=0.95,
            recovery_bull_exposure=0.75,
            range_bound_exposure=0.45,
        ),
        RadarCoreVariant(
            name="radar_core_v1_defensive_weekly",
            label="雷達核心成員池 v1 防守週頻",
            top_theme_count=1,
            max_stocks_per_theme=2,
            max_single_weight=0.25,
            min_theme_score=0.16,
            min_stock_score=0.08,
            overheated_20d_return=0.45,
            strong_bull_exposure=0.75,
            recovery_bull_exposure=0.50,
            range_bound_exposure=0.20,
            correction_bear_exposure=0.0,
        ),
        RadarCoreVariant(
            name="radar_core_v1_leader_weekly",
            label="雷達核心成員池 v1 領頭股週頻",
            top_theme_count=2,
            max_stocks_per_theme=1,
            max_single_weight=0.40,
            min_theme_score=0.12,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=0.90,
            recovery_bull_exposure=0.65,
            range_bound_exposure=0.30,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
        ),
        RadarCoreVariant(
            name="radar_core_v1_leader_monthly",
            label="雷達核心成員池 v1 領頭股月頻",
            rebalance_frequency="monthly",
            top_theme_count=2,
            max_stocks_per_theme=1,
            max_single_weight=0.40,
            min_theme_score=0.12,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=0.90,
            recovery_bull_exposure=0.65,
            range_bound_exposure=0.30,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
        ),
        RadarCoreVariant(
            name="radar_core_v1_defensive_monthly",
            label="雷達核心成員池 v1 防守月頻",
            rebalance_frequency="monthly",
            top_theme_count=1,
            max_stocks_per_theme=2,
            max_single_weight=0.25,
            min_theme_score=0.16,
            min_stock_score=0.08,
            overheated_20d_return=0.45,
            strong_bull_exposure=0.75,
            recovery_bull_exposure=0.50,
            range_bound_exposure=0.20,
            correction_bear_exposure=0.0,
        ),
        RadarCoreVariant(
            name="radar_core_v1_defensive_weekly_blowoff_std",
            label="雷達核心成員池 v1 防守週頻 + blow-off 標準防守",
            top_theme_count=1,
            max_stocks_per_theme=2,
            max_single_weight=0.25,
            min_theme_score=0.16,
            min_stock_score=0.08,
            overheated_20d_return=0.45,
            strong_bull_exposure=0.75,
            recovery_bull_exposure=0.50,
            range_bound_exposure=0.20,
            correction_bear_exposure=0.0,
            daily_blowoff_exit=True,
            blowoff_min_runup_20d=0.25,
            blowoff_drawdown_10d=-0.08,
            blowoff_volume_ratio_5d_over_60d=1.5,
        ),
        RadarCoreVariant(
            name="radar_core_v1_defensive_weekly_blowoff_fast",
            label="雷達核心成員池 v1 防守週頻 + blow-off 敏感防守",
            top_theme_count=1,
            max_stocks_per_theme=2,
            max_single_weight=0.25,
            min_theme_score=0.16,
            min_stock_score=0.08,
            overheated_20d_return=0.45,
            strong_bull_exposure=0.75,
            recovery_bull_exposure=0.50,
            range_bound_exposure=0.20,
            correction_bear_exposure=0.0,
            daily_blowoff_exit=True,
            blowoff_min_runup_20d=0.20,
            blowoff_drawdown_10d=-0.06,
            blowoff_volume_ratio_5d_over_60d=1.2,
        ),
        RadarCoreVariant(
            name="radar_core_v1_leader_weekly_blowoff_std",
            label="雷達核心成員池 v1 領頭股週頻 + blow-off 標準防守",
            top_theme_count=2,
            max_stocks_per_theme=1,
            max_single_weight=0.40,
            min_theme_score=0.12,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=0.90,
            recovery_bull_exposure=0.65,
            range_bound_exposure=0.30,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
            daily_blowoff_exit=True,
            blowoff_min_runup_20d=0.25,
            blowoff_drawdown_10d=-0.08,
            blowoff_volume_ratio_5d_over_60d=1.5,
        ),
        RadarCoreVariant(
            name="radar_core_v1_leader_weekly_blowoff_fast",
            label="雷達核心成員池 v1 領頭股週頻 + blow-off 敏感防守",
            top_theme_count=2,
            max_stocks_per_theme=1,
            max_single_weight=0.40,
            min_theme_score=0.12,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=0.90,
            recovery_bull_exposure=0.65,
            range_bound_exposure=0.30,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
            daily_blowoff_exit=True,
            blowoff_min_runup_20d=0.20,
            blowoff_drawdown_10d=-0.06,
            blowoff_volume_ratio_5d_over_60d=1.2,
        ),
        RadarCoreVariant(
            name="radar_core_v1_defensive_weekly_exposure_boost",
            label="雷達核心成員池 v1 防守選股 + 多頭曝險提高",
            top_theme_count=1,
            max_stocks_per_theme=2,
            max_single_weight=0.35,
            min_theme_score=0.16,
            min_stock_score=0.08,
            overheated_20d_return=0.45,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=0.75,
            range_bound_exposure=0.35,
            correction_bear_exposure=0.0,
        ),
        RadarCoreVariant(
            name="radar_core_v1_defensive_weekly_concentrated",
            label="雷達核心成員池 v1 防守選股 + 單題材集中",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=0.60,
            min_theme_score=0.16,
            min_stock_score=0.08,
            overheated_20d_return=0.45,
            strong_bull_exposure=0.90,
            recovery_bull_exposure=0.65,
            range_bound_exposure=0.25,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
        ),
        RadarCoreVariant(
            name="radar_core_v1_defensive_weekly_top2_leaders",
            label="雷達核心成員池 v1 防守選股 + 兩題材領頭",
            top_theme_count=2,
            max_stocks_per_theme=1,
            max_single_weight=0.40,
            min_theme_score=0.14,
            min_stock_score=0.08,
            overheated_20d_return=0.45,
            strong_bull_exposure=0.95,
            recovery_bull_exposure=0.70,
            range_bound_exposure=0.30,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
        ),
        RadarCoreVariant(
            name="radar_core_v1_defensive_weekly_relaxed_theme",
            label="雷達核心成員池 v1 防守選股 + 放寬題材門檻",
            top_theme_count=1,
            max_stocks_per_theme=2,
            max_single_weight=0.30,
            min_theme_score=0.12,
            min_stock_score=0.08,
            overheated_20d_return=0.45,
            strong_bull_exposure=0.95,
            recovery_bull_exposure=0.70,
            range_bound_exposure=0.30,
            correction_bear_exposure=0.0,
        ),
        RadarCoreVariant(
            name="radar_core_v1_concentrated_full_exposure",
            label="雷達核心成員池 v1 單題材單股 + 曝險提高",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.16,
            min_stock_score=0.08,
            overheated_20d_return=0.45,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=0.75,
            range_bound_exposure=0.35,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
        ),
        RadarCoreVariant(
            name="radar_core_v1_concentrated_overheat65",
            label="雷達核心成員池 v1 單題材單股 + 放寬過熱65%",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=0.80,
            min_theme_score=0.16,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=0.95,
            recovery_bull_exposure=0.70,
            range_bound_exposure=0.30,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
        ),
        RadarCoreVariant(
            name="radar_core_v1_concentrated_relaxed_score",
            label="雷達核心成員池 v1 單題材單股 + 放寬分數門檻",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=0.80,
            min_theme_score=0.12,
            min_stock_score=0.06,
            overheated_20d_return=0.65,
            strong_bull_exposure=0.95,
            recovery_bull_exposure=0.70,
            range_bound_exposure=0.30,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
        ),
        RadarCoreVariant(
            name="radar_core_v1_single_theme_top2_full",
            label="雷達核心成員池 v1 單題材雙股 + 曝險提高",
            top_theme_count=1,
            max_stocks_per_theme=2,
            max_single_weight=0.50,
            min_theme_score=0.16,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=0.75,
            range_bound_exposure=0.35,
            correction_bear_exposure=0.0,
        ),
        RadarCoreVariant(
            name="radar_core_v1_concentrated_full_blowoff_std",
            label="雷達核心成員池 v1 單題材單股 + 曝險提高 + blow-off 標準",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.16,
            min_stock_score=0.08,
            overheated_20d_return=0.45,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=0.75,
            range_bound_exposure=0.35,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
            daily_blowoff_exit=True,
            blowoff_min_runup_20d=0.25,
            blowoff_drawdown_10d=-0.08,
            blowoff_volume_ratio_5d_over_60d=1.5,
        ),
        RadarCoreVariant(
            name="radar_core_v1_concentrated_full_blowoff_fast",
            label="雷達核心成員池 v1 單題材單股 + 曝險提高 + blow-off 敏感",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.16,
            min_stock_score=0.08,
            overheated_20d_return=0.45,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=0.75,
            range_bound_exposure=0.35,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
            daily_blowoff_exit=True,
            blowoff_min_runup_20d=0.20,
            blowoff_drawdown_10d=-0.06,
            blowoff_volume_ratio_5d_over_60d=1.2,
        ),
        RadarCoreVariant(
            name="radar_core_v1_concentrated_full_aggressive_regime",
            label="雷達核心成員池 v1 單題材單股 + 積極環境曝險",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.16,
            min_stock_score=0.08,
            overheated_20d_return=0.45,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=0.90,
            range_bound_exposure=0.50,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
        ),
        RadarCoreVariant(
            name="radar_core_v1_concentrated_full_relaxed_theme",
            label="雷達核心成員池 v1 單題材單股 + 曝險提高 + 題材門檻放寬",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.12,
            min_stock_score=0.08,
            overheated_20d_return=0.45,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=0.75,
            range_bound_exposure=0.35,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
        ),
        RadarCoreVariant(
            name="radar_core_v1_concentrated_regime_balanced",
            label="雷達核心成員池 v1 單題材單股 + 環境平衡曝險",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.16,
            min_stock_score=0.08,
            overheated_20d_return=0.45,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=0.80,
            range_bound_exposure=0.30,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
        ),
        RadarCoreVariant(
            name="radar_core_v1_concentrated_regime_guarded",
            label="雷達核心成員池 v1 單題材單股 + 環境防守曝險",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.16,
            min_stock_score=0.08,
            overheated_20d_return=0.45,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=0.70,
            range_bound_exposure=0.15,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
        ),
        RadarCoreVariant(
            name="radar_core_v1_concentrated_regime_strict",
            label="雷達核心成員池 v1 單題材單股 + 嚴格多頭才進攻",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.16,
            min_stock_score=0.08,
            overheated_20d_return=0.45,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=0.55,
            range_bound_exposure=0.0,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
        ),
        RadarCoreVariant(
            name="radar_core_v1_concentrated_regime_high_bar",
            label="雷達核心成員池 v1 單題材單股 + 高門檻環境平衡",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.10,
            overheated_20d_return=0.45,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=0.80,
            range_bound_exposure=0.25,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
        ),
        RadarCoreVariant(
            name="radar_core_v1_concentrated_aggressive_overheat65",
            label="雷達核心成員池 v1 單題材單股 + 積極曝險 + 過熱65%",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.16,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=0.90,
            range_bound_exposure=0.50,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
        ),
        RadarCoreVariant(
            name="radar_core_v1_concentrated_aggressive_overheat90",
            label="雷達核心成員池 v1 單題材單股 + 積極曝險 + 過熱90%",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.16,
            min_stock_score=0.08,
            overheated_20d_return=0.90,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=0.90,
            range_bound_exposure=0.50,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
        ),
        RadarCoreVariant(
            name="radar_core_v1_concentrated_aggressive_no_overheat",
            label="雷達核心成員池 v1 單題材單股 + 積極曝險 + 不擋過熱",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.16,
            min_stock_score=0.08,
            overheated_20d_return=9.99,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=0.90,
            range_bound_exposure=0.50,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
        ),
        RadarCoreVariant(
            name="radar_core_v1_concentrated_aggressive_relaxed_score",
            label="雷達核心成員池 v1 單題材單股 + 積極曝險 + 分數放寬",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.12,
            min_stock_score=0.06,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=0.90,
            range_bound_exposure=0.50,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
        ),
        RadarCoreVariant(
            name="radar_core_v1_global_leader_top2_overheat45",
            label="雷達核心成員池 v1 前二題材最強股 + 過熱45%",
            top_theme_count=2,
            max_stocks_per_theme=1,
            max_total_stocks=1,
            max_single_weight=1.0,
            min_theme_score=0.16,
            min_stock_score=0.08,
            overheated_20d_return=0.45,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=0.90,
            range_bound_exposure=0.50,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
            selection_mode="global_leaders",
        ),
        RadarCoreVariant(
            name="radar_core_v1_global_leader_top3_overheat45",
            label="雷達核心成員池 v1 前三題材最強股 + 過熱45%",
            top_theme_count=3,
            max_stocks_per_theme=1,
            max_total_stocks=1,
            max_single_weight=1.0,
            min_theme_score=0.16,
            min_stock_score=0.08,
            overheated_20d_return=0.45,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=0.90,
            range_bound_exposure=0.50,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
            selection_mode="global_leaders",
        ),
        RadarCoreVariant(
            name="radar_core_v1_global_leader_top3_overheat65",
            label="雷達核心成員池 v1 前三題材最強股 + 過熱65%",
            top_theme_count=3,
            max_stocks_per_theme=1,
            max_total_stocks=1,
            max_single_weight=1.0,
            min_theme_score=0.16,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=0.90,
            range_bound_exposure=0.50,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
            selection_mode="global_leaders",
        ),
        RadarCoreVariant(
            name="radar_core_v1_global_leader_top5_overheat65",
            label="雷達核心成員池 v1 前五題材最強股 + 過熱65%",
            top_theme_count=5,
            max_stocks_per_theme=1,
            max_total_stocks=1,
            max_single_weight=1.0,
            min_theme_score=0.16,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=0.90,
            range_bound_exposure=0.50,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
            selection_mode="global_leaders",
        ),
        RadarCoreVariant(
            name="radar_core_v1_concentrated_aggressive_theme20_overheat65",
            label="雷達核心成員池 v1 單題材單股 + 題材20門檻 + 過熱65%",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=0.90,
            range_bound_exposure=0.50,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
        ),
        RadarCoreVariant(
            name="radar_core_v1_concentrated_aggressive_theme25_overheat65",
            label="雷達核心成員池 v1 單題材單股 + 題材25門檻 + 過熱65%",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.25,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=0.90,
            range_bound_exposure=0.50,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
        ),
        RadarCoreVariant(
            name="radar_core_v1_concentrated_aggressive_theme30_overheat65",
            label="雷達核心成員池 v1 單題材單股 + 題材30門檻 + 過熱65%",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.30,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=0.90,
            range_bound_exposure=0.50,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
        ),
        RadarCoreVariant(
            name="radar_core_v1_concentrated_aggressive_theme25_stock12_overheat65",
            label="雷達核心成員池 v1 單題材單股 + 題材25股票12門檻",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.25,
            min_stock_score=0.12,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=0.90,
            range_bound_exposure=0.50,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
        ),
        RadarCoreVariant(
            name="radar_core_v1_concentrated_theme20_weak25x60_overheat65",
            label="雷達核心成員池 v1 題材20 + 弱題材60%曝險",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=0.90,
            range_bound_exposure=0.50,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
            weak_theme_full_score=0.25,
            weak_theme_exposure_multiplier=0.60,
        ),
        RadarCoreVariant(
            name="radar_core_v1_concentrated_theme20_weak25x40_overheat65",
            label="雷達核心成員池 v1 題材20 + 弱題材40%曝險",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=0.90,
            range_bound_exposure=0.50,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
            weak_theme_full_score=0.25,
            weak_theme_exposure_multiplier=0.40,
        ),
        RadarCoreVariant(
            name="radar_core_v1_concentrated_theme20_weak30x60_overheat65",
            label="雷達核心成員池 v1 題材20 + 30以下60%曝險",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=0.90,
            range_bound_exposure=0.50,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
            weak_theme_full_score=0.30,
            weak_theme_exposure_multiplier=0.60,
        ),
        RadarCoreVariant(
            name="radar_core_v1_concentrated_theme20_weak30x30_overheat65",
            label="雷達核心成員池 v1 題材20 + 30以下30%曝險",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=0.90,
            range_bound_exposure=0.50,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
            weak_theme_full_score=0.30,
            weak_theme_exposure_multiplier=0.30,
        ),
        RadarCoreVariant(
            name="radar_core_v1_concentrated_aggressive_theme20_overheat65_daily",
            label="雷達核心成員池 v1 題材20過熱65 + 日頻",
            rebalance_frequency="daily",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=0.90,
            range_bound_exposure=0.50,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
        ),
        RadarCoreVariant(
            name="radar_core_v1_concentrated_aggressive_theme20_overheat65_daily_band03",
            label="雷達核心成員池 v1 題材20過熱65 + 日頻低容忍",
            rebalance_frequency="daily",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=0.90,
            range_bound_exposure=0.50,
            correction_bear_exposure=0.0,
            rebalance_band=0.03,
        ),
        RadarCoreVariant(
            name="radar_core_v1_concentrated_full_aggressive_regime_daily",
            label="雷達核心成員池 v1 積極環境曝險 + 日頻",
            rebalance_frequency="daily",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.16,
            min_stock_score=0.08,
            overheated_20d_return=0.45,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=0.90,
            range_bound_exposure=0.50,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
        ),
        RadarCoreVariant(
            name="radar_core_v1_concentrated_theme20_overheat65_hold90",
            label="雷達核心成員池 v1 題材20過熱65 + 持有90%",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=0.90,
            range_bound_exposure=0.50,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
            hold_existing_score_ratio=0.90,
        ),
        RadarCoreVariant(
            name="radar_core_v1_concentrated_theme20_overheat65_hold85",
            label="雷達核心成員池 v1 題材20過熱65 + 持有85%",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=0.90,
            range_bound_exposure=0.50,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
            hold_existing_score_ratio=0.85,
        ),
        RadarCoreVariant(
            name="radar_core_v1_concentrated_theme20_overheat65_hold75",
            label="雷達核心成員池 v1 題材20過熱65 + 持有75%",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=0.90,
            range_bound_exposure=0.50,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
            hold_existing_score_ratio=0.75,
        ),
        RadarCoreVariant(
            name="radar_core_v1_concentrated_theme20_overheat65_trend_ma10",
            label="雷達核心成員池 v1 題材20過熱65 + MA10退出",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=0.90,
            range_bound_exposure=0.50,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
            daily_trend_exit=True,
            trend_exit_ma_window=10,
            trend_exit_drawdown_20d=-0.99,
        ),
        RadarCoreVariant(
            name="radar_core_v1_concentrated_theme20_overheat65_trend_ma20",
            label="雷達核心成員池 v1 題材20過熱65 + MA20退出",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=0.90,
            range_bound_exposure=0.50,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
            daily_trend_exit=True,
            trend_exit_ma_window=20,
            trend_exit_drawdown_20d=-0.99,
        ),
        RadarCoreVariant(
            name="radar_core_v1_concentrated_theme20_overheat65_trend_dd10",
            label="雷達核心成員池 v1 題材20過熱65 + 回撤10退出",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=0.90,
            range_bound_exposure=0.50,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
            daily_trend_exit=True,
            trend_exit_ma_window=2,
            trend_exit_drawdown_20d=-0.10,
        ),
        RadarCoreVariant(
            name="radar_core_v1_concentrated_theme20_overheat65_biweekly",
            label="雷達核心成員池 v1 題材20過熱65 + 兩週頻",
            rebalance_frequency="biweekly",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=0.90,
            range_bound_exposure=0.50,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
        ),
        RadarCoreVariant(
            name="radar_core_v1_concentrated_theme20_overheat65_monthly",
            label="雷達核心成員池 v1 題材20過熱65 + 月頻",
            rebalance_frequency="monthly",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=0.90,
            range_bound_exposure=0.50,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
        ),
        RadarCoreVariant(
            name="radar_core_v1_single_theme_top2_theme20_overheat65",
            label="雷達核心成員池 v1 單題材雙股 + 題材20過熱65",
            top_theme_count=1,
            max_stocks_per_theme=2,
            max_single_weight=0.50,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=0.90,
            range_bound_exposure=0.50,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
        ),
        RadarCoreVariant(
            name="radar_core_v1_single_theme_top2_theme20_overheat65_biweekly",
            label="雷達核心成員池 v1 單題材雙股 + 題材20過熱65 + 兩週頻",
            rebalance_frequency="biweekly",
            top_theme_count=1,
            max_stocks_per_theme=2,
            max_single_weight=0.50,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=0.90,
            range_bound_exposure=0.50,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
        ),
        RadarCoreVariant(
            name="radar_core_v1_concentrated_theme20_overheat65_full_non_bear",
            label="雷達核心成員池 v1 題材20過熱65 + 非空頭滿倉",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
        ),
        RadarCoreVariant(
            name="radar_core_v1_concentrated_theme20_overheat65_range75",
            label="雷達核心成員池 v1 題材20過熱65 + 震盪75%",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=0.75,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
        ),
        RadarCoreVariant(
            name="radar_core_v1_concentrated_theme16_overheat65_full_non_bear",
            label="雷達核心成員池 v1 題材16過熱65 + 非空頭滿倉",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.16,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
        ),
        RadarCoreVariant(
            name="radar_core_v1_concentrated_theme20_overheat90_full_non_bear",
            label="雷達核心成員池 v1 題材20過熱90 + 非空頭滿倉",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.90,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
        ),
        RadarCoreVariant(
            name="radar_core_v1_concentrated_theme20_overheat65_correction50",
            label="雷達核心成員池 v1 題材20過熱65 + 修正50%",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=0.50,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
        ),
        RadarCoreVariant(
            name="radar_core_v1_concentrated_theme20_overheat65_correction100",
            label="雷達核心成員池 v1 題材20過熱65 + 修正滿倉",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
        ),
        RadarCoreVariant(
            name="radar_core_v1_theme20_corr100_portstop10_cd5",
            label="雷達核心成員池 v1 題材20修正滿倉 + 組合回撤10%冷卻5日",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            portfolio_trailing_stop=True,
            portfolio_stop_drawdown=-0.10,
            portfolio_stop_cooldown_days=5,
        ),
        RadarCoreVariant(
            name="radar_core_v1_theme20_corr100_portstop12_cd5",
            label="雷達核心成員池 v1 題材20修正滿倉 + 組合回撤12%冷卻5日",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            portfolio_trailing_stop=True,
            portfolio_stop_drawdown=-0.12,
            portfolio_stop_cooldown_days=5,
        ),
        RadarCoreVariant(
            name="radar_core_v1_theme20_corr100_portstop15_cd5",
            label="雷達核心成員池 v1 題材20修正滿倉 + 組合回撤15%冷卻5日",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            portfolio_trailing_stop=True,
            portfolio_stop_drawdown=-0.15,
            portfolio_stop_cooldown_days=5,
        ),
        RadarCoreVariant(
            name="radar_core_v1_theme20_corr100_portstop12_cd10",
            label="雷達核心成員池 v1 題材20修正滿倉 + 組合回撤12%冷卻10日",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            portfolio_trailing_stop=True,
            portfolio_stop_drawdown=-0.12,
            portfolio_stop_cooldown_days=10,
        ),
        RadarCoreVariant(
            name="radar_core_v1_theme20_corr100_gain200_stop12_cd5",
            label="雷達核心成員池 v1 題材20修正滿倉 + 獲利200%後回撤12%冷卻5日",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            portfolio_trailing_stop=True,
            portfolio_stop_drawdown=-0.12,
            portfolio_stop_cooldown_days=5,
            portfolio_stop_min_gain=2.0,
        ),
        RadarCoreVariant(
            name="radar_core_v1_theme20_corr100_gain200_stop15_cd5",
            label="雷達核心成員池 v1 題材20修正滿倉 + 獲利200%後回撤15%冷卻5日",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            portfolio_trailing_stop=True,
            portfolio_stop_drawdown=-0.15,
            portfolio_stop_cooldown_days=5,
            portfolio_stop_min_gain=2.0,
        ),
        RadarCoreVariant(
            name="radar_core_v1_theme20_corr100_gain300_stop12_cd5",
            label="雷達核心成員池 v1 題材20修正滿倉 + 獲利300%後回撤12%冷卻5日",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            portfolio_trailing_stop=True,
            portfolio_stop_drawdown=-0.12,
            portfolio_stop_cooldown_days=5,
            portfolio_stop_min_gain=3.0,
        ),
        RadarCoreVariant(
            name="radar_core_v1_theme20_corr100_gain300_stop15_cd5",
            label="雷達核心成員池 v1 題材20修正滿倉 + 獲利300%後回撤15%冷卻5日",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            portfolio_trailing_stop=True,
            portfolio_stop_drawdown=-0.15,
            portfolio_stop_cooldown_days=5,
            portfolio_stop_min_gain=3.0,
        ),
        RadarCoreVariant(
            name="radar_core_v1_theme20_corr100_posrun20_stop12_cd5",
            label="雷達核心成員池 v1 題材20修正滿倉 + 個股獲利20%後回撤12%",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            position_trailing_stop=True,
            position_stop_min_runup=0.20,
            position_stop_drawdown=-0.12,
            position_stop_cooldown_days=5,
        ),
        RadarCoreVariant(
            name="radar_core_v1_theme20_corr100_posrun30_stop12_cd5",
            label="雷達核心成員池 v1 題材20修正滿倉 + 個股獲利30%後回撤12%",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            position_trailing_stop=True,
            position_stop_min_runup=0.30,
            position_stop_drawdown=-0.12,
            position_stop_cooldown_days=5,
        ),
        RadarCoreVariant(
            name="radar_core_v1_theme20_corr100_posrun30_stop15_cd5",
            label="雷達核心成員池 v1 題材20修正滿倉 + 個股獲利30%後回撤15%",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            position_trailing_stop=True,
            position_stop_min_runup=0.30,
            position_stop_drawdown=-0.15,
            position_stop_cooldown_days=5,
        ),
        RadarCoreVariant(
            name="radar_core_v1_theme20_corr100_posrun40_stop15_cd5",
            label="雷達核心成員池 v1 題材20修正滿倉 + 個股獲利40%後回撤15%",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            position_trailing_stop=True,
            position_stop_min_runup=0.40,
            position_stop_drawdown=-0.15,
            position_stop_cooldown_days=5,
        ),
        RadarCoreVariant(
            name="radar_core_v1_theme20_corr100_overheat70",
            label="雷達核心成員池 v1 題材20修正滿倉 + 過熱70",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.70,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
        ),
        RadarCoreVariant(
            name="radar_core_v1_theme20_corr100_overheat75",
            label="雷達核心成員池 v1 題材20修正滿倉 + 過熱75",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.75,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
        ),
        RadarCoreVariant(
            name="radar_core_v1_theme20_corr100_overheat80",
            label="雷達核心成員池 v1 題材20修正滿倉 + 過熱80",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.80,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
        ),
        RadarCoreVariant(
            name="radar_core_v1_theme20_corr100_overheat75_stock12",
            label="雷達核心成員池 v1 題材20修正滿倉 + 過熱75 + 個股分數12",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.12,
            overheated_20d_return=0.75,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
        ),
        RadarCoreVariant(
            name="radar_core_v1_global_top1_theme3_corr100",
            label="雷達核心成員池 v1 前三題材全域最強1檔 + 修正滿倉",
            top_theme_count=3,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            selection_mode="global_leaders",
            max_total_stocks=1,
        ),
        RadarCoreVariant(
            name="radar_core_v1_global_top1_theme5_corr100",
            label="雷達核心成員池 v1 前五題材全域最強1檔 + 修正滿倉",
            top_theme_count=5,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            selection_mode="global_leaders",
            max_total_stocks=1,
        ),
        RadarCoreVariant(
            name="radar_core_v1_global_top2_theme3_corr100",
            label="雷達核心成員池 v1 前三題材全域最強2檔 + 修正滿倉",
            top_theme_count=3,
            max_stocks_per_theme=1,
            max_single_weight=0.50,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            selection_mode="global_leaders",
            max_total_stocks=2,
        ),
        RadarCoreVariant(
            name="radar_core_v1_theme3_per_theme1_corr100",
            label="雷達核心成員池 v1 前三題材各挑1檔 + 修正滿倉",
            top_theme_count=3,
            max_stocks_per_theme=1,
            max_single_weight=0.50,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
        ),
        RadarCoreVariant(
            name="radar_core_v1_theme20_corr100_score_short_momentum",
            label="雷達核心成員池 v1 題材20修正滿倉 + 短動能分數",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="short_momentum",
        ),
        RadarCoreVariant(
            name="radar_core_v1_theme20_corr100_score_trend_momentum",
            label="雷達核心成員池 v1 題材20修正滿倉 + 趨勢動能分數",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="trend_momentum",
        ),
        RadarCoreVariant(
            name="radar_core_v1_theme20_corr100_score_risk_adjusted",
            label="雷達核心成員池 v1 題材20修正滿倉 + 風險調整分數",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="risk_adjusted",
        ),
        RadarCoreVariant(
            name="radar_core_v1_theme20_corr100_score_theme_relative",
            label="雷達核心成員池 v1 題材20修正滿倉 + 同族群相對強度",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="risk_adjusted_theme_relative",
        ),
        RadarCoreVariant(
            name="radar_core_v1_theme20_corr100_score_theme_relative_stock12",
            label="雷達核心成員池 v1 題材20修正滿倉 + 同族群相對強度 + 分數12",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.12,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="risk_adjusted_theme_relative",
        ),
        RadarCoreVariant(
            name="radar_core_v1_theme20_corr100_score_capital_flow",
            label="雷達核心成員池 v1 題材20修正滿倉 + 同族群資金集中",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="risk_adjusted_capital_flow",
        ),
        RadarCoreVariant(
            name="radar_core_v1_theme20_corr100_score_theme_leader_stock12",
            label="雷達核心成員池 v1 題材20修正滿倉 + 題材領頭股 + 分數12",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.12,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="risk_adjusted_theme_leader",
        ),
        RadarCoreVariant(
            name="radar_core_v1_score_risk_corr75",
            label="雷達核心成員池 v1 風險調整分數 + 修正市75%",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=0.75,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="risk_adjusted",
        ),
        RadarCoreVariant(
            name="radar_core_v1_score_risk_corr50",
            label="雷達核心成員池 v1 風險調整分數 + 修正市50%",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=0.50,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="risk_adjusted",
        ),
        RadarCoreVariant(
            name="radar_core_v1_score_risk_corr25",
            label="雷達核心成員池 v1 風險調整分數 + 修正市25%",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=0.25,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="risk_adjusted",
        ),
        RadarCoreVariant(
            name="radar_core_v1_score_risk_range75_corr50",
            label="雷達核心成員池 v1 風險調整分數 + 震盪75修正50",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=0.75,
            correction_bear_exposure=0.50,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="risk_adjusted",
        ),
        RadarCoreVariant(
            name="radar_core_v1_theme20_corr100_score_raw_momentum",
            label="雷達核心成員池 v1 題材20修正滿倉 + 純動能分數",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="raw_momentum",
        ),
        RadarCoreVariant(
            name="radar_core_v1_score_risk_overheat70",
            label="雷達核心成員池 v1 風險調整分數 + 過熱70",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.70,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="risk_adjusted",
        ),
        RadarCoreVariant(
            name="radar_core_v1_score_risk_overheat75",
            label="雷達核心成員池 v1 風險調整分數 + 過熱75",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.75,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="risk_adjusted",
        ),
        RadarCoreVariant(
            name="radar_core_v1_score_risk_hold90",
            label="雷達核心成員池 v1 風險調整分數 + 持有90%",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="risk_adjusted",
            hold_existing_score_ratio=0.90,
        ),
        RadarCoreVariant(
            name="radar_core_v1_score_risk_trend_ma20",
            label="雷達核心成員池 v1 風險調整分數 + MA20退出",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="risk_adjusted",
            daily_trend_exit=True,
            trend_exit_ma_window=20,
            trend_exit_drawdown_20d=-0.99,
        ),
        RadarCoreVariant(
            name="radar_core_v1_score_risk_daily",
            label="雷達核心成員池 v1 風險調整分數 + 日頻",
            rebalance_frequency="daily",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="risk_adjusted",
        ),
        RadarCoreVariant(
            name="radar_core_v1_score_risk_theme15",
            label="雷達核心成員池 v1 風險調整分數 + 題材15",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.15,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="risk_adjusted",
        ),
        RadarCoreVariant(
            name="radar_core_v1_score_risk_theme25",
            label="雷達核心成員池 v1 風險調整分數 + 題材25",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.25,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="risk_adjusted",
        ),
        RadarCoreVariant(
            name="radar_core_v1_score_risk_stock05",
            label="雷達核心成員池 v1 風險調整分數 + 個股05",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.05,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="risk_adjusted",
        ),
        RadarCoreVariant(
            name="radar_core_v1_score_risk_stock00",
            label="雷達核心成員池 v1 風險調整分數 + 個股00",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.00,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="risk_adjusted",
        ),
        RadarCoreVariant(
            name="radar_core_v1_score_risk_stock03",
            label="雷達核心成員池 v1 風險調整分數 + 個股03",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.03,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="risk_adjusted",
        ),
        RadarCoreVariant(
            name="radar_core_v1_score_risk_stock06",
            label="雷達核心成員池 v1 風險調整分數 + 個股06",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.06,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="risk_adjusted",
        ),
        RadarCoreVariant(
            name="radar_core_v1_score_risk_stock00_turnover50m",
            label="雷達核心成員池 v1 風險調整分數 + 個股00 + 流動性50M",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_avg_turnover_twd=50_000_000,
            min_theme_score=0.20,
            min_stock_score=0.00,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="risk_adjusted",
        ),
        RadarCoreVariant(
            name="radar_core_v1_score_risk_stock00_turnover40m",
            label="雷達核心成員池 v1 風險調整分數 + 個股00 + 流動性40M",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_avg_turnover_twd=40_000_000,
            min_theme_score=0.20,
            min_stock_score=0.00,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="risk_adjusted",
        ),
        RadarCoreVariant(
            name="radar_core_v1_score_risk_stock00_turnover60m",
            label="雷達核心成員池 v1 風險調整分數 + 個股00 + 流動性60M",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_avg_turnover_twd=60_000_000,
            min_theme_score=0.20,
            min_stock_score=0.00,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="risk_adjusted",
        ),
        RadarCoreVariant(
            name="radar_core_v1_score_risk_stock00_turnover70m",
            label="雷達核心成員池 v1 風險調整分數 + 個股00 + 流動性70M",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_avg_turnover_twd=70_000_000,
            min_theme_score=0.20,
            min_stock_score=0.00,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="risk_adjusted",
        ),
        RadarCoreVariant(
            name="radar_core_v1_score_risk_stock00_turnover100m",
            label="雷達核心成員池 v1 風險調整分數 + 個股00 + 流動性100M",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_avg_turnover_twd=100_000_000,
            min_theme_score=0.20,
            min_stock_score=0.00,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="risk_adjusted",
        ),
        RadarCoreVariant(
            name="radar_core_v1_score_risk_stock00_turnover120m",
            label="雷達核心成員池 v1 風險調整分數 + 個股00 + 流動性120M",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_avg_turnover_twd=120_000_000,
            min_theme_score=0.20,
            min_stock_score=0.00,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="risk_adjusted",
        ),
        RadarCoreVariant(
            name="radar_core_v1_score_risk_stock00_turnover200m",
            label="雷達核心成員池 v1 風險調整分數 + 個股00 + 流動性200M",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_avg_turnover_twd=200_000_000,
            min_theme_score=0.20,
            min_stock_score=0.00,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="risk_adjusted",
        ),
        RadarCoreVariant(
            name="radar_core_v1_score_theme_relative_stock00_turnover60m",
            label="雷達核心成員池 v1 同族群相對強度 + 個股00 + 流動性60M",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_avg_turnover_twd=60_000_000,
            min_theme_score=0.20,
            min_stock_score=0.00,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="risk_adjusted_theme_relative",
        ),
        RadarCoreVariant(
            name="radar_core_v1_score_risk_stock00_turnover60m_overheat55",
            label="雷達核心成員池 v1 風險調整分數 + 流動性60M + 過熱55",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_avg_turnover_twd=60_000_000,
            min_theme_score=0.20,
            min_stock_score=0.00,
            overheated_20d_return=0.55,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="risk_adjusted",
        ),
        RadarCoreVariant(
            name="radar_core_v1_score_risk_stock00_turnover60m_overheat60",
            label="雷達核心成員池 v1 風險調整分數 + 流動性60M + 過熱60",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_avg_turnover_twd=60_000_000,
            min_theme_score=0.20,
            min_stock_score=0.00,
            overheated_20d_return=0.60,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="risk_adjusted",
        ),
        RadarCoreVariant(
            name="radar_core_v1_score_risk_stock00_turnover60m_overheat58",
            label="雷達核心成員池 v1 風險調整分數 + 流動性60M + 過熱58",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_avg_turnover_twd=60_000_000,
            min_theme_score=0.20,
            min_stock_score=0.00,
            overheated_20d_return=0.58,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="risk_adjusted",
        ),
        radar_core_mid_small_calibrated_v1_variant(),
        RadarCoreVariant(
            name="radar_core_v1_score_risk_stock00_turnover60m_overheat64",
            label="雷達核心成員池 v1 風險調整分數 + 流動性60M + 過熱64",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_avg_turnover_twd=60_000_000,
            min_theme_score=0.20,
            min_stock_score=0.00,
            overheated_20d_return=0.64,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="risk_adjusted",
        ),
        RadarCoreVariant(
            name="radar_core_v1_score_risk_stock00_turnover60m_overheat70",
            label="雷達核心成員池 v1 風險調整分數 + 流動性60M + 過熱70",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_avg_turnover_twd=60_000_000,
            min_theme_score=0.20,
            min_stock_score=0.00,
            overheated_20d_return=0.70,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="risk_adjusted",
        ),
        RadarCoreVariant(
            name="radar_core_v1_score_risk_stock00_turnover60m_overheat75",
            label="雷達核心成員池 v1 風險調整分數 + 流動性60M + 過熱75",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_avg_turnover_twd=60_000_000,
            min_theme_score=0.20,
            min_stock_score=0.00,
            overheated_20d_return=0.75,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="risk_adjusted",
        ),
        RadarCoreVariant(
            name="radar_core_v1_score_raw_stock00_turnover60m",
            label="雷達核心成員池 v1 純動能 + 個股00 + 流動性60M",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_avg_turnover_twd=60_000_000,
            min_theme_score=0.20,
            min_stock_score=0.00,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="raw_momentum",
        ),
        RadarCoreVariant(
            name="radar_core_v1_score_trend_stock00_turnover60m",
            label="雷達核心成員池 v1 趨勢動能 + 個股00 + 流動性60M",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_avg_turnover_twd=60_000_000,
            min_theme_score=0.20,
            min_stock_score=0.00,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="trend_momentum",
        ),
        RadarCoreVariant(
            name="radar_core_v1_score_risk_stock00_top2_half",
            label="雷達核心成員池 v1 風險調整分數 + 個股00 + 兩題材各半",
            top_theme_count=2,
            max_stocks_per_theme=1,
            max_single_weight=0.5,
            min_theme_score=0.20,
            min_stock_score=0.00,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="risk_adjusted",
        ),
        RadarCoreVariant(
            name="radar_core_v1_score_risk_stock12",
            label="雷達核心成員池 v1 風險調整分數 + 個股12",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.12,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="risk_adjusted",
        ),
        RadarCoreVariant(
            name="radar_core_v1_theme20_corr100_score_risk_weekly_tue",
            label="雷達核心成員池 v1 風險調整分數 + 週二調倉",
            rebalance_frequency="weekly_tue",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="risk_adjusted",
        ),
        RadarCoreVariant(
            name="radar_core_v1_theme20_corr100_score_risk_weekly_wed",
            label="雷達核心成員池 v1 風險調整分數 + 週三調倉",
            rebalance_frequency="weekly_wed",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="risk_adjusted",
        ),
        RadarCoreVariant(
            name="radar_core_v1_theme20_corr100_score_risk_weekly_thu",
            label="雷達核心成員池 v1 風險調整分數 + 週四調倉",
            rebalance_frequency="weekly_thu",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="risk_adjusted",
        ),
        RadarCoreVariant(
            name="radar_core_v1_theme20_corr100_score_risk_weekly_fri",
            label="雷達核心成員池 v1 風險調整分數 + 週五調倉",
            rebalance_frequency="weekly_fri",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="risk_adjusted",
        ),
        RadarCoreVariant(
            name="radar_core_v1_concentrated_theme25_overheat65_correction50",
            label="雷達核心成員池 v1 題材25過熱65 + 修正50%",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.25,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=0.50,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
        ),
        RadarCoreVariant(
            name="radar_core_v1_concentrated_theme25_overheat65_correction100",
            label="雷達核心成員池 v1 題材25過熱65 + 修正滿倉",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.25,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
        ),
        RadarCoreVariant(
            name="radar_core_v1_accel_theme20_overheat65_base",
            label="雷達核心成員池 v1 資金加速 + 題材20過熱65",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=0.90,
            range_bound_exposure=0.50,
            correction_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="acceleration",
        ),
        RadarCoreVariant(
            name="radar_core_v1_accel_theme20_overheat65_correction50",
            label="雷達核心成員池 v1 資金加速 + 題材20修正50%",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=0.50,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="acceleration",
        ),
        RadarCoreVariant(
            name="radar_core_v1_accel_theme20_overheat65_correction100",
            label="雷達核心成員池 v1 資金加速 + 題材20修正滿倉",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=1.0,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="acceleration",
        ),
        RadarCoreVariant(
            name="radar_core_v1_accel_theme20_overheat65_ma20_only_correction50",
            label="雷達核心成員池 v1 資金加速 + MA20 + 修正50%",
            top_theme_count=1,
            max_stocks_per_theme=1,
            max_single_weight=1.0,
            min_theme_score=0.20,
            min_stock_score=0.08,
            overheated_20d_return=0.65,
            strong_bull_exposure=1.0,
            recovery_bull_exposure=1.0,
            range_bound_exposure=1.0,
            correction_bear_exposure=0.50,
            systemic_bear_exposure=0.0,
            rebalance_band=0.08,
            stock_score_mode="acceleration",
            require_ma60=False,
        ),
    ]


def _download_member_prices(
    members: list[ThemeMember],
    *,
    start_date: str,
    end_date: str,
    cache_dir: str | Path,
    cache_only: bool = False,
) -> tuple[list[ThemeMember], dict[str, pd.DataFrame], list[dict[str, str]]]:
    resolved: list[ThemeMember] = []
    prices: dict[str, pd.DataFrame] = {}
    skipped: list[dict[str, str]] = []
    for member in members:
        error_text = ""
        for ticker in _exchange_candidates(member.symbol, cache_dir):
            if cache_only:
                csv_path = Path(cache_dir) / f"{ticker.replace('.', '_')}.csv"
                if not csv_path.exists():
                    error_text = "cache_missing"
                    continue
                loaded = load_price_csv(csv_path)
                if not _covers_requested_range(loaded, start_date, end_date):
                    error_text = "cache_range_not_covered"
                    continue
                prices[ticker] = loaded
                resolved.append(replace(member, ticker=ticker))
                break
            try:
                downloaded = download_yfinance_prices([ticker], start_date=start_date, end_date=end_date, cache_dir=cache_dir)
            except Exception as error:  # noqa: BLE001 - try TW/TWO candidates before skipping.
                error_text = str(error)
                continue
            prices[ticker] = downloaded[ticker]
            resolved.append(replace(member, ticker=ticker))
            break
        else:
            skipped.append({"symbol": member.symbol, "name": member.name, "theme": member.theme, "reason": error_text})
    return resolved, prices, skipped


def _load_cached_prices(tickers: list[str], start_date: str, end_date: str, cache_dir: str | Path) -> dict[str, pd.DataFrame]:
    prices: dict[str, pd.DataFrame] = {}
    missing: list[str] = []
    for ticker in tickers:
        path = Path(cache_dir) / f"{ticker.replace('.', '_')}.csv"
        if not path.exists():
            missing.append(f"{ticker}: cache_missing")
            continue
        loaded = load_price_csv(path)
        if not _covers_requested_range(loaded, start_date, end_date):
            missing.append(f"{ticker}: cache_range_not_covered")
            continue
        prices[ticker] = loaded
    if missing:
        raise ValueError("; ".join(missing))
    return prices


def _covers_requested_range(frame: pd.DataFrame, start_date: str, end_date: str) -> bool:
    if frame.empty:
        return False
    start = pd.Timestamp(start_date)
    end = pd.Timestamp(end_date)
    start_gap_days = (frame.index.min() - start).days
    end_gap_days = (end - frame.index.max()).days
    return start_gap_days <= 10 and end_gap_days <= 10


def _exchange_candidates(symbol: str, cache_dir: str | Path) -> list[str]:
    cache_path = Path(cache_dir)
    tw = f"{symbol}.TW"
    two = f"{symbol}.TWO"
    two_cache = cache_path / f"{two.replace('.', '_')}.csv"
    tw_cache = cache_path / f"{tw.replace('.', '_')}.csv"
    if two_cache.exists() and not tw_cache.exists():
        return [two, tw]
    return [tw, two]


def _write_variant_outputs(output_dir: Path, variant: RadarCoreVariant, result: RadarCoreResult) -> None:
    prefix = variant.name
    result.result.equity_curve.reset_index().to_csv(output_dir / f"{prefix}_equity_curve.csv", index=False, encoding="utf-8-sig")
    result.holdings.to_csv(output_dir / f"{prefix}_holdings.csv", index=False, encoding="utf-8-sig")
    result.theme_log.to_csv(output_dir / f"{prefix}_theme_log.csv", index=False, encoding="utf-8-sig")
    result.stock_log.to_csv(output_dir / f"{prefix}_stock_log.csv", index=False, encoding="utf-8-sig")
    pd.DataFrame([trade.__dict__ for trade in result.result.trades]).to_csv(output_dir / f"{prefix}_trades.csv", index=False, encoding="utf-8-sig")


def _write_summary(
    output_dir: Path,
    variant_results: list[tuple[RadarCoreVariant, RadarCoreResult]],
    benchmarks: list[BacktestResult],
    skipped: list[dict[str, str]],
    args: argparse.Namespace,
    run_started: str,
) -> None:
    rows = []
    for variant, result in variant_results:
        rows.append(_summary_row(variant.label, result.result, "radar_core_pool_v1", variant.name))
    for benchmark in benchmarks:
        rows.append(_summary_row(benchmark.name, benchmark, "benchmark", benchmark.name))
    summary = pd.DataFrame(rows).sort_values("total_return_pct", ascending=False)
    summary.to_csv(output_dir / "radar_core_pool_v1_summary.csv", index=False, encoding="utf-8-sig")
    pd.DataFrame(skipped).to_csv(output_dir / "radar_core_pool_v1_skipped_members.csv", index=False, encoding="utf-8-sig")
    metadata = {
        "run_started": run_started,
        "run_finished": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "start_date": args.start_date,
        "end_date": args.end_date,
        "warmup_start": args.warmup_start,
        "themes": args.themes or "all_primary_themes",
        "output_dir": str(output_dir),
        "note": "雷達核心成員池 v1 是中小型題材股研究模型；大型權值股最佳版只作機會成本參考，不是設計來源。",
    }
    (output_dir / "metadata.json").write_text(json.dumps(metadata, ensure_ascii=False, indent=2), encoding="utf-8")
    _write_report(output_dir / "radar_core_pool_v1_report.md", summary, skipped, metadata)


def _summary_row(label: str, result: BacktestResult, group: str, variant_id: str) -> dict:
    return {
        "group": group,
        "variant_id": variant_id,
        "label": label,
        "final_value": round(result.final_value, 2),
        "total_return_pct": round(result.total_return * 100, 2),
        "max_drawdown_pct": round(result.max_drawdown * 100, 2),
        "trades": len(result.trades),
    }


def _write_report(path: Path, summary: pd.DataFrame, skipped: list[dict[str, str]], metadata: dict) -> None:
    lines = [
        "# 雷達核心成員池 v1 初始驗證",
        "",
        f"- 區間：{metadata['start_date']} ~ {metadata['end_date']}",
        f"- 暖身起點：{metadata['warmup_start']}",
        f"- 題材範圍：{metadata['themes']}",
        "- 定位：中小型題材股研究模型；不是投資建議。",
        "- 比較口徑：0050/0050正二是市場對照；大型權值股最佳版另作機會成本參考。",
        "",
        "## 排名",
        "",
        _markdown_table(summary),
        "",
        "## 資料限制",
        "",
        f"- 無法取得或跳過成員數：{len(skipped)}",
        "- 回測使用 signal_date 以前資料；交易日開盤才依前一交易日訊號換倉。",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")


def _markdown_table(frame: pd.DataFrame) -> str:
    if frame.empty:
        return "_無資料_"
    columns = list(frame.columns)
    lines = [
        "| " + " | ".join(columns) + " |",
        "| " + " | ".join(["---"] * len(columns)) + " |",
    ]
    for _, row in frame.iterrows():
        lines.append("| " + " | ".join(str(row[column]) for column in columns) + " |")
    return "\n".join(lines)


def _write_step(output_dir: Path, step: str) -> None:
    (output_dir / "current_step.txt").write_text(step, encoding="utf-8")


def _append_log(output_dir: Path, variant_id: str, status: str, detail: str) -> None:
    path = output_dir / "run_log.csv"
    exists = path.exists()
    with path.open("a", newline="", encoding="utf-8-sig") as handle:
        writer = csv.DictWriter(handle, fieldnames=["timestamp", "variant_id", "status", "detail"])
        if not exists:
            writer.writeheader()
        writer.writerow(
            {
                "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                "variant_id": variant_id,
                "status": status,
                "detail": detail,
            }
        )


def _read_completed(path: Path) -> set[str]:
    if not path.exists():
        return set()
    frame = pd.read_csv(path)
    if "variant_id" not in frame:
        return set()
    return set(frame["variant_id"].astype(str))


def _append_completed(output_dir: Path, variant: RadarCoreVariant, result: BacktestResult) -> None:
    path = output_dir / "completed_variants.csv"
    exists = path.exists()
    with path.open("a", newline="", encoding="utf-8-sig") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=["timestamp", "variant_id", "label", "final_value", "total_return_pct", "max_drawdown_pct", "trades"],
        )
        if not exists:
            writer.writeheader()
        writer.writerow(_completed_row(variant, result))


def _completed_row(variant: RadarCoreVariant, result: BacktestResult) -> dict:
    return {
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "variant_id": variant.name,
        "label": variant.label,
        "final_value": round(result.final_value, 2),
        "total_return_pct": round(result.total_return * 100, 2),
        "max_drawdown_pct": round(result.max_drawdown * 100, 2),
        "trades": len(result.trades),
    }


def _append_failed(output_dir: Path, variant: RadarCoreVariant, error: Exception) -> None:
    path = output_dir / "failed_variants.csv"
    exists = path.exists()
    with path.open("a", newline="", encoding="utf-8-sig") as handle:
        writer = csv.DictWriter(handle, fieldnames=["timestamp", "variant_id", "label", "error"])
        if not exists:
            writer.writeheader()
        writer.writerow(
            {
                "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                "variant_id": variant.name,
                "label": variant.label,
                "error": str(error),
            }
        )


if __name__ == "__main__":
    main()
