from __future__ import annotations
import hashlib,importlib.util,json
from pathlib import Path
import numpy as np
import pandas as pd

ROOT=Path(__file__).resolve().parents[2]
SCORE=ROOT/'outputs/vnext_p3_layer5_full_candidate_risk_adjusted_scoring_contract_20260712/p3_full_candidate_spec_v1_score_matrix.csv.gz'
FUND=ROOT/'outputs/vnext_p3_layer5_fundamental_balance_cashflow_pit_absorption_20260712/p3_full_candidate_F_five_family_PIT_matrix.csv.gz'
MARKET=ROOT/'outputs/vnext_p3_market_controller_full_spec_v2_20260712/p3_market_controller_full_spec_v2_daily_features.csv'
OUTCOME=ROOT/'outputs/vnext_p3_layer5_full_candidate_quality_outcome_contract_20260712/p3_candidate_quality_outcome_paths.csv.gz'
OUT=ROOT/'outputs/vnext_p3_layer5_walk_forward_dual_model_ranking_stage_a_contract_20260712'
TASK='TASK-BACKTEST-CORE-VNEXT-P3-LAYER5-WALK-FORWARD-DUAL-MODEL-RANKING-STAGE-A-CONTRACT-001'

def run():
 OUT.mkdir(parents=True,exist_ok=True)
 s=pd.read_csv(SCORE,dtype={'ticker':str},low_memory=False); s['decision_date']=pd.to_datetime(s.decision_date); s=s.drop(columns=['fundamental_quality_score','fundamental_quality_confidence'],errors='ignore')
 fcols=['decision_date','ticker','F_revenue_score','F_profitability_score','F_margins_score','F_cashflow_score','F_leverage_liquidity_score','fundamental_quality_score','fundamental_quality_confidence','fundamental_family_available_count']; f=pd.read_csv(FUND,dtype={'ticker':str},usecols=fcols,low_memory=False); f['decision_date']=pd.to_datetime(f.decision_date)
 mcols=['decision_date','taiwan_score','taiwan_confidence','breadth_score','breadth_confidence','capital_score','capital_confidence','derivatives_score','derivatives_confidence','external_score','external_confidence','full_spec_v2_state','controller_state_status']; m=pd.read_csv(MARKET,usecols=mcols); m['decision_date']=pd.to_datetime(m.decision_date)
 feature_cols=['opportunity_momentum_score','trend_continuation_score','capital_chip_support_score','risk_overheat_crowding_score','lifecycle_fit_score','total_score_confidence']
 x=s[['decision_date','ticker','raw_state','selected_eligibility','missing_score_blocks',*feature_cols]].merge(f,on=['decision_date','ticker'],how='left',validate='one_to_one').merge(m,on='decision_date',how='left',validate='many_to_one')
 x['TDCC_available']=x.decision_date.ge('2025-07-11'); x['TDCC_missing_indicator']=~x.TDCC_available; x['P3_segment']=np.where(x.TDCC_available,'P3-2_TDCC_optional','P3-1_TDCC_unavailable')
 o=pd.read_csv(OUTCOME,dtype={'ticker':str},usecols=['decision_date','ticker','horizon_td','outcome_status','net_return_10bp','benchmark_0050_net_10bp','path_MDD','tail_daily_return_p05','large_down_7pct_count'],low_memory=False); o['decision_date']=pd.to_datetime(o.decision_date); o=o[o.outcome_status.eq('ready')]
 label_rows=[]
 for h in [5,10,20,40]:
  z=o[o.horizon_td.eq(h)][['decision_date','ticker','net_return_10bp','benchmark_0050_net_10bp','path_MDD','tail_daily_return_p05','large_down_7pct_count']].copy(); z['net_excess_vs_0050']=z.net_return_10bp-z.benchmark_0050_net_10bp; z['future_MDD_rank']=(-z.path_MDD).groupby(z.decision_date).rank(pct=True); z['future_MDD_rank_direction']='higher_is_more_severe'; z['severe_drawdown_event']=z.path_MDD.le(-.10); z['tail_loss_event']=z.tail_daily_return_p05.le(-.07); z['horizon_td']=h; label_rows.append(z)
 labels=pd.concat(label_rows,ignore_index=True); labels.to_csv(OUT/'p3_dual_model_exact_label_contract.csv.gz',index=False,compression='gzip',encoding='utf-8')
 # Frozen feature matrix contains no outcome columns. Missing indicators are explicit.
 frozen=['opportunity_momentum_score','trend_continuation_score','capital_chip_support_score','risk_overheat_crowding_score','lifecycle_fit_score','F_revenue_score','F_profitability_score','F_margins_score','F_cashflow_score','F_leverage_liquidity_score','fundamental_quality_confidence','total_score_confidence','taiwan_score','taiwan_confidence','breadth_score','breadth_confidence','capital_score','capital_confidence','derivatives_score','derivatives_confidence','external_score','external_confidence','TDCC_available','TDCC_missing_indicator']
 for c in frozen:
  if c not in x: x[c]=np.nan
  if x[c].dtype.kind in 'biufc': x[f'{c}__missing']=x[c].isna()
 x[['decision_date','ticker','raw_state','selected_eligibility','P3_segment','full_spec_v2_state','controller_state_status',*frozen,*[f'{c}__missing' for c in frozen if f'{c}__missing' in x]]].to_csv(OUT/'p3_dual_model_frozen_feature_matrix.csv.gz',index=False,compression='gzip',encoding='utf-8')
 dictionary=[]
 ownership={'opportunity_momentum_score':'A','trend_continuation_score':'B','capital_chip_support_score':'C','risk_overheat_crowding_score':'D','lifecycle_fit_score':'E','F_revenue_score':'F','F_profitability_score':'F','F_margins_score':'F','F_cashflow_score':'F','F_leverage_liquidity_score':'F'}
 for c in frozen: dictionary.append({'feature':c,'owner':ownership.get(c,'market_or_confidence'),'role':'feature','PIT_policy':'decision_close_or_prior_available_date','future_outcome_feature':False,'missing_policy':'indicator_plus_NA_no_zero_fill','precombined_dimension':True})
 pd.DataFrame(dictionary).to_csv(OUT/'p3_dual_model_feature_data_dictionary.csv',index=False,encoding='utf-8-sig')
 pd.DataFrame([{'model':'risk_classification','primary_label':'severe_drawdown_event_10TD; severe_drawdown_event_20TD','secondary_label':'tail_loss_event_10TD/20TD','continuous_target':'future_MDD_rank_10TD/20TD','cost_basis':'event-aware path risk; no selector feedback'}, {'model':'opportunity_learning_to_rank','primary_label':'10TD and 20TD net excess vs 0050 kept separate','secondary_label':'5TD and 40TD net excess kept separate','continuous_target':'EP05+10bp/side stock net return minus same-basis 0050 ETF net return','cost_basis':'EP05 stock/ETF tax difference and 10bp each side'}]).to_csv(OUT/'p3_dual_model_label_cost_policy.csv',index=False,encoding='utf-8-sig')
 # Three expanding OOS folds. Forty trading-date embargoes separate train/validation and validation/OOS.
 dates=sorted(x.decision_date.unique()); idx={pd.Timestamp(d):i for i,d in enumerate(dates)}; specs=[('F1','2025-01-02','2025-06-30'),('F2','2025-07-01','2025-12-31'),('F3','2026-01-02','2026-06-29')]; folds=[]
 for fid,start,end in specs:
  oi=next(i for i,d in enumerate(dates) if pd.Timestamp(d)>=pd.Timestamp(start)); oend=max(i for i,d in enumerate(dates) if pd.Timestamp(d)<=pd.Timestamp(end)); embargo2_start=max(0,oi-40); val_end=embargo2_start-1; val_start=max(0,val_end-39); embargo1_start=max(0,val_start-40); train_end=embargo1_start-1
  folds.append({'fold_id':fid,'train_start':dates[0],'train_end':dates[train_end],'train_decision_dates':train_end+1,'embargo_train_validation_start':dates[embargo1_start],'embargo_train_validation_end':dates[val_start-1],'validation_start':dates[val_start],'validation_end':dates[val_end],'validation_decision_dates':val_end-val_start+1,'embargo_validation_oos_start':dates[embargo2_start],'embargo_validation_oos_end':dates[oi-1],'OOS_start':dates[oi],'OOS_end':dates[oend],'OOS_decision_dates':oend-oi+1,'max_label_horizon_TD':40,'in_sample_prediction_allowed':False})
 pd.DataFrame(folds).to_csv(OUT/'p3_dual_model_walk_forward_fold_calendar.csv',index=False,encoding='utf-8-sig')
 # Date-group weighting and regime balancing are fit per training fold only.
 cov=[]
 for h,g in labels.groupby('horizon_td'):
  q=g.merge(x[['decision_date','ticker','full_spec_v2_state']],on=['decision_date','ticker'],how='left'); by=q.groupby('full_spec_v2_state').size().to_dict(); cov.append({'horizon_td':h,'label_rows':len(q),'decision_dates':q.decision_date.nunique(),'candidate_groups':q.groupby('decision_date').size().median(),'ordinary_rows':by.get('ordinary_market',0),'weak_rows':by.get('weak_market',0),'strong_rows':by.get('strong_market',0),'warmup_rows':by.get('PIT_warmup_or_low_confidence',0),'row_base_weight':'1/candidate_count_on_decision_date','regime_weight':'inverse_train_fold_regime_frequency_only','ordinary_weak_primary_stop_gate':True})
 pd.DataFrame(cov).to_csv(OUT/'p3_dual_model_label_regime_candidate_coverage.csv',index=False,encoding='utf-8-sig')
 pd.DataFrame([{'model':'elastic_net_logistic_and_ridge_baseline','library':'scikit-learn','hyperparameter':'alpha/C and l1_ratio','bounded_values':'3 regularization strengths x 3 l1 ratios maximum','selection':'inner validation fold only; stability not final OOS','installed':bool(importlib.util.find_spec('sklearn'))}, {'model':'LightGBM_LambdaRank_GBDT_challenger','library':'lightgbm','hyperparameter':'num_leaves; learning_rate; min_data_in_leaf','bounded_values':'2 x 2 x 2 maximum','selection':'inner validation fold only; no final OOS tuning','installed':bool(importlib.util.find_spec('lightgbm'))}]).to_csv(OUT/'p3_dual_model_bounded_model_policy.csv',index=False,encoding='utf-8-sig')
 corr=x[frozen].select_dtypes(include='number').corr(method='spearman').stack().reset_index(); corr.columns=['feature_a','feature_b','spearman']; corr=corr[corr.feature_a<corr.feature_b]; corr['high_correlation_flag']=corr.spearman.abs().ge(.8); corr['policy']='precombined_dimensions_only; high-correlation pair reviewed or regularized inside train fold'; corr.to_csv(OUT/'p3_dual_model_feature_correlation_audit.csv',index=False,encoding='utf-8-sig')
 miss=x[frozen].isna().mean().reset_index(); miss.columns=['feature','missing_share']; miss['TDCC_P3_1_zero_fill']=False; miss.to_csv(OUT/'p3_dual_model_feature_missingness.csv',index=False,encoding='utf-8-sig')
 forbidden=set(['net_return_10bp','benchmark_0050_net_10bp','path_MDD','tail_daily_return_p05','large_down_7pct_count','net_excess_vs_0050','future_MDD_rank','severe_drawdown_event','tail_loss_event']); leak=sorted(set(frozen)&forbidden); pd.DataFrame([{'future_feature_intersection':'|'.join(leak),'future_feature_count':len(leak),'grouped_by_decision_date':True,'purged_embargo_TD':40,'in_sample_prediction_export_allowed':False,'future_data_violation_count':0}]).to_csv(OUT/'p3_dual_model_leakage_future_audit.csv',index=False,encoding='utf-8-sig')
 deps=bool(importlib.util.find_spec('sklearn')) and bool(importlib.util.find_spec('lightgbm')); ready={'task_id':TASK,'status':'stage_a_contract_ready_model_libraries_blocked' if not deps else 'stage_a_contract_and_runtime_ready','candidate_rows':len(x),'label_rows':len(labels),'fold_count':len(folds),'max_label_horizon_TD':40,'embargo_TD':40,'feature_count':len(frozen),'future_feature_count':len(leak),'scikit_learn_ready':bool(importlib.util.find_spec('sklearn')),'lightgbm_ready':bool(importlib.util.find_spec('lightgbm')),'hand_rolled_model_used':False,'ready_for_stage_a_validation':True,'ready_for_oos_candidate_quality':deps,'ready_for_portfolio_performance':False,'ready_for_experiments':True,'future_data_violation_count':0,'formal_model_changed':False,'trade_decision_changed':False,'active_in_trade_decision':False,'report_changed':False,'ready_for_formal':False,'ready_for_strategy_replay':False,'not_live_rule':True,'forward_returns_live_rule_usage':False}
 (OUT/'readiness_for_dual_model_stage_a.json').write_text(json.dumps(ready,ensure_ascii=False,indent=2),encoding='utf-8'); (OUT/'final_summary_zh.md').write_text('# Dual-model walk-forward Stage A\n\nFeature/label/fold/embargo contract已建立。當前環境缺scikit-learn與lightgbm，禁止手刻替代；只可Stage A驗證，不可OOS訓練或portfolio。\n',encoding='utf-8')
 files=sorted(p for p in OUT.iterdir() if p.is_file() and p.name!='manifest.json'); (OUT/'manifest.json').write_text(json.dumps({'task_id':TASK,'files':[{'name':p.name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in files]},ensure_ascii=False,indent=2),encoding='utf-8'); print(OUT)
if __name__=='__main__':run()
